name: Lint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.toml"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**/*.toml"

jobs:
  taplo-lint:
    name: taplo lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: uncenter/setup-taplo@v1
        with:
          version: "0.8.1"

      - run: taplo fmt --check
