name: Test Mypy

on:
  push:
    branches:
      - main
    paths:
      - "sunray/**/*.py"
      - "tests/mypy/*.yaml"
      - noxfile.py
      - poetry.lock
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "sunray/**/*.py"
      - "tests/mypy/*.yaml"
      - noxfile.py
      - poetry.lock

jobs:
  mypy-tests:
    name: mypy tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.11"

      - name: Set up nox
        run: pip install nox

      - name: Set up cache
        uses: actions/cache@v4
        id: cache
        with:
          path: .nox
          key: nox-mypy-${{ hashFiles('noxfile.py') }}

      - name: Run mypy test
        run: |
          nox -s test_mypy

      - name: Check for clean working tree
        run: |
          git diff --exit-code --stat HEAD
